In [2]:
import pandas as pd
import re
import unicodedata

In [ ]:
sommeil = pd.read_csv("cleanedwpays.csv")
sommeil.drop_duplicates(subset=['PMID'], keep='last', inplace=True) # supprimer les doublons
sommeil = sommeil[sommeil["Pays"]!="Inconnu"] # garder les lignes où le pays n'est pas inconnu
sommeil = sommeil[sommeil["Pays"]!="Andorra"] # si le pays c'est Andorra on ne garde pas


# Nettoyage des résumés
def clean_text(text):
    if isinstance(text, str):
        text = re.sub(r"\n+", " ", text)  # Supprimer les retours à la ligne multiples
        text = re.sub(r"\s+", " ", text).strip()  # Supprimer les espaces en trop
    return text

sommeil["Résumé"] = sommeil["Résumé"].apply(clean_text)

sommeil

,Titre,Date de publication,Lien,Résumé,Mots-clés,Auteurs,Affiliations,PMID,Maladie,Auteurs_Affiliations,Pays
0,Sleep characteristics and cerebrospinal fluid ...,2020-08,https://pubmed.ncbi.nlm.nih.gov//32657026/,Introduction: This study tested the self-repor...,alzheimers disease; amyloid cerebrospinal flui...,"Wei Xu, 1, Lan Tan, 1, Bing-Jie Su, 1, Huan Yu...","1 Department of Neurology, Qingdao Municipal H...",32657026,Alzheimer,"[('Wei Xu', ['Department of Neurology, Qingdao...",China
1,Sleep Disturbance and Alzheimer's Disease: The...,2022-07,https://pubmed.ncbi.nlm.nih.gov//35303225/,Poor quality and quantity of sleep are very co...,alzheimer’s disease; amyloid beta; astrocyte; ...,"Aditya Sunkaria, #, 1, Supriya Bhardwaj, #, 2","1 Department of Biotechnology, Guru Nanak Dev ...",35303225,Alzheimer,"[('Aditya Sunkaria', ['Department of Biotechno...",India
2,Association of Sleep With Risk of Alzheimer's ...,2022-04,https://pubmed.ncbi.nlm.nih.gov//34109847/,Objectives: Alzheimer's disease (AD) and relat...,alzheimer’s disease; american association of r...,"Aaron C Schneider, 1, Chooza Moon, 1, Kara Whi...","1 University of Iowa, Iowa City, USA.; 2 The U...",34109847,Alzheimer,"[('Aaron C Schneider', ['University of Iowa, I...",United States
3,Sleep oscillation-specific associations with A...,2019-02,https://pubmed.ncbi.nlm.nih.gov//30791922/,Background: Based on associations between slee...,tau sleep spindle csf density,"Korey Kam, 1, Ankit Parekh, 1, Ram A Sharma, 2...","1 Mount Sinai Integrative Sleep Center, Divisi...",30791922,Alzheimer,"[('Korey Kam', ['Mount Sinai Integrative Sleep...",United States
4,Tailored music listening intervention to reduc...,2020-12,https://pubmed.ncbi.nlm.nih.gov//33136301/,Sleep disruption in older adults living with A...,alzheimers disease; dementia; music; sleep,"Darina V Petrovsky, 1, Nalaka S Gooneratne, 2,...","1 Behavioral Health Sciences Department, Unive...",33136301,Alzheimer,"[('Darina V Petrovsky', ['Behavioral Health Sc...",United States
...,...,...,...,...,...,...,...,...,...,...,...
34959,Comprehensive evaluation of diabetes subtypes ...,2025-02,https://pubmed.ncbi.nlm.nih.gov//40022072/,Background: The traditional binary classificat...,diabetes subtypes; diet; education; exercise; ...,"Nathalie Rohmann, #, 1, 2, Johannes Epe, #, 1,...",1 Institute of Diabetes and Clinical Metabolic...,40022072,Obesite,"[('Nathalie Rohmann', ['Institute of Diabetes ...",Germany
34960,Associations of an overall healthy lifestyle w...,2024-11,https://pubmed.ncbi.nlm.nih.gov//39587552/,Background: Metabolic dysfunction-associated f...,fatty liver disease; hepatic steatosis; lifest...,"Caimei Yuan, #, 1, Chengjing Zhang, #, 2, Xin ...","1 CAS Key Laboratory of Nutrition, Metabolism ...",39587552,Obesite,"[('Caimei Yuan', ['CAS Key Laboratory of Nutri...",China
34961,[Epidemiological characteristics of early-onse...,2024-05,https://pubmed.ncbi.nlm.nih.gov//38778685/,Objective: To explore the differences in distr...,v eocrc patient χ,"T Jin, 1, Y S Zhu, 1, C C Liu, 1, X Xu, 2, W L...","1 Department of Colorectal Surgery, Oncology (...",38778685,Obesite,"[('T Jin', ['Department of Colorectal Surgery,...",China
34963,Factors that influence participation in physic...,2024-06,https://pubmed.ncbi.nlm.nih.gov//38837220/,Background: Mental health problems contribute ...,physical activity health bipolar study,"Claire J McCartan, 1, Jade Yap, 2, Paul Best, ...","1 IMPACT Research Centre, Northern Health & So...",38837220,Obesite,"[('Claire J McCartan', ['IMPACT Research Centr...",United Kingdom
34966,Recommendations from the 2023 International Ev...,2023-10,https://pubmed.ncbi.nlm.nih.gov//37589624/,Study question: What is the recommended assess...,grade; polycystic ovary syndrome; assessment; ...,"Helena J Teede, 1, Chau Thien Tay, 2, Joop Lav...",1 Monash Centre for Health Research and Implem...,37589624,Obesite,"[('Helena J Teede', ['Monash Centre for Health...",Australia

In [ ]:
#Supprime les accents et normalise les textes pour éviter des erreurs lors de l'insertion dans la bd

def nettoyer_texte(texte):
    if isinstance(texte, str):
        texte = unicodedata.normalize('NFKD', texte).encode('ASCII', 'ignore').decode('utf-8')
    return texte

#### Table article

In [ ]:
# Table Articles
articles = sommeil[['PMID', 'Titre', 'Date de publication', 'Pays']].copy().drop_duplicates()
articles.rename(columns={'Date de publication': 'Date_pub'}, inplace=True)

articles['Titre'] = articles['Titre'].apply(nettoyer_texte)
articles['Pays'] = articles['Pays'].apply(nettoyer_texte)


# enregistrer en CSV
articles.to_csv("articles.csv", index=False)
articles

,PMID,Titre,Date_pub,Pays
0,32657026,Sleep characteristics and cerebrospinal fluid ...,2020-08,China
1,35303225,Sleep Disturbance and Alzheimer's Disease: The...,2022-07,India
2,34109847,Association of Sleep With Risk of Alzheimer's ...,2022-04,United States
3,30791922,Sleep oscillation-specific associations with A...,2019-02,United States
4,33136301,Tailored music listening intervention to reduc...,2020-12,United States
...,...,...,...,...
34959,40022072,Comprehensive evaluation of diabetes subtypes ...,2025-02,Germany
34960,39587552,Associations of an overall healthy lifestyle w...,2024-11,China
34961,38778685,[Epidemiological characteristics of early-onse...,2024-05,China
34963,38837220,Factors that influence participation in physic...,2024-06,United Kingdom
34966,37589624,Recommendations from the 2023 International Ev...,2023-10,Australia

#### Table auteurs

In [ ]:
# Extraction des auteurs et affiliations
auteurs_list = []
for row in sommeil['Auteurs_Affiliations'].dropna():
    try:
        auteurs_affiliations = eval(row)
        for auteur, affiliations in auteurs_affiliations:
            if affiliations:
                auteurs_list.append((auteur, affiliations[0]))  # Prendre la 1ère affiliation
    except:
        print(f"erreur de format sur la ligne : {row}")

auteurs = pd.DataFrame(auteurs_list, columns=['Nom', 'Affiliation']).drop_duplicates()

auteurs['Nom'] = auteurs['Nom'].apply(nettoyer_texte)
auteurs['Affiliation'] = auteurs['Affiliation'].apply(nettoyer_texte)


auteurs

                       Nom                                        Affiliation
0                   Wei Xu  Department of Neurology, Qingdao Municipal Hos...
1                  Lan Tan  Department of Neurology, Qingdao Municipal Hos...
2              Bing-Jie Su  Department of Neurology, Qingdao Municipal Hos...
3                  Huan Yu  Department of Neurology and Institute of Neuro...
4               Yan-Lin Bi  Department of Anesthesiology, Qingdao Municipa...
...                    ...                                                ...
136496     Leanne M Redman  Pennington Biomedical Research Center, Louisia...
136497  Jacqueline A Boyle  National Health and Medical Research Council C...
136498     Robert J Norman  National Health and Medical Research Council C...
136499           Aya Mousa  Monash Centre for Health Research and Implemen...
136500        Anju E Joham  Monash Centre for Health Research and Implemen...

[131643 rows x 2 columns]

In [ ]:
# Limiter à 1000 caractères les affiliation trop longue car erreur lors de l'insertion dans la bd
auteurs["Affiliation"] = auteurs["Affiliation"].str.slice(0, 1000)
auteurs.to_csv("auteurs.csv", index = False, encoding="utf-8")

In [15]:
auteurs

                       Nom                                        Affiliation
0                   Wei Xu  Department of Neurology, Qingdao Municipal Hos...
1                  Lan Tan  Department of Neurology, Qingdao Municipal Hos...
2              Bing-Jie Su  Department of Neurology, Qingdao Municipal Hos...
3                  Huan Yu  Department of Neurology and Institute of Neuro...
4               Yan-Lin Bi  Department of Anesthesiology, Qingdao Municipa...
...                    ...                                                ...
136496     Leanne M Redman  Pennington Biomedical Research Center, Louisia...
136497  Jacqueline A Boyle  National Health and Medical Research Council C...
136498     Robert J Norman  National Health and Medical Research Council C...
136499           Aya Mousa  Monash Centre for Health Research and Implemen...
136500        Anju E Joham  Monash Centre for Health Research and Implemen...

[131643 rows x 2 columns]

#### Maladie

In [ ]:
# Extraction des maladies uniques
maladies = sommeil[['Maladie']].drop_duplicates().rename(columns={'Maladie': 'Nom'})

# enregistrer en CSV
maladies.to_csv("maladies.csv", index=False)
maladies

                           Nom
0                    Alzheimer
3792                    Cancer
12574                  Diabete
19773  Hypertension Arterielle
26882                  Obesite

#### Mots clés

In [ ]:
# Extraction des mots-clés
mots_cles_set = set()
for mots in sommeil['Mots-clés'].dropna():
    for mot in mots.split(";"):
        mots_cles_set.add(mot.strip())

mots_cles = pd.DataFrame(mots_cles_set, columns=['Mots_cles']).drop_duplicates()
mots_cles['Mots_cles'] = mots_cles['Mots_cles'].apply(nettoyer_texte)
mots_cles.drop_duplicates(inplace=True)


# enregistrer en CSV
mots_cles.to_csv("mots_cles.csv", index=False)
mots_cles

                                               Mots_cles
0                                            han chinese
1                                        risk assessment
2                                    hidratos de carbono
3                                            botulinum a
4                                 burning mouth syndrome
...                                                  ...
27188  minimally invasive retroperitoneal pancreatic ...
27189                           short sleep habitual min
27190                               family impact survey
27191                     occupational physical activity
27192                                      sedentariness

[26954 rows x 1 columns]

In [ ]:
mots_cles["Mots_cles"].nunique() #verifier que tous les mots-clés sont uniques

26954

#### creation de fichiers qui vont aider à alimenter les tables d'associations

#### Ecrire

In [ ]:
# Extraction des relations Auteur ↔ Article
ecrire_list = []
for row in sommeil[['PMID', 'Auteurs_Affiliations']].dropna().values:
    pmid, auteurs_affiliations = row
    try:
        auteurs_affiliations = eval(auteurs_affiliations)
        for auteur, affiliations in auteurs_affiliations:
            if affiliations:
                ecrire_list.append((auteur, affiliations[0], pmid))
    except:
        print(f"erreur de format sur la ligne : {row}")

ecrire = pd.DataFrame(ecrire_list, columns=['Auteur_nom', 'Auteur_affiliation', 'Article_pmid']).drop_duplicates()
ecrire['Auteur_nom'] = ecrire['Auteur_nom'].apply(nettoyer_texte)
ecrire['Auteur_affiliation'] = ecrire['Auteur_affiliation'].apply(nettoyer_texte)
ecrire["Auteur_affiliation"] = ecrire["Auteur_affiliation"].str.slice(0, 1000)
ecrire


ecrire.to_csv("ecriretemp.csv", index=False)

Réduction de la table ecrire trop lourde pour la bd

In [ ]:
ecrire_temp = pd.read_csv("ecriretemp.csv")

# Compter le nombre d'articles uniques écrits par chaque auteur
auteur_counts = ecrire_temp.groupby(['Auteur_nom', 'Auteur_affiliation'])['Article_pmid'].nunique().reset_index(name='nb_articles')

# Trier par nombre d’articles décroissant et garder le top 20
top_auteurs = auteur_counts.sort_values(by='nb_articles', ascending=False).head(10000)

ecrire_reduit = ecrire_temp.merge(top_auteurs[['Auteur_nom', 'Auteur_affiliation']], on=['Auteur_nom', 'Auteur_affiliation'])

ecrire_reduit.to_csv("ecrire.csv", index=False)
ecrire_reduit

,Auteur_nom,Auteur_affiliation,Article_pmid
0,Yan-Lin Bi,"Department of Anesthesiology, Qingdao Municipa...",32657026
1,Ankit Parekh,"Mount Sinai Integrative Sleep Center, Division...",30791922
2,Andreia Andrade,"Department of Psychiatry, NYU School of Medici...",30791922
3,Andrew W Varga,"Mount Sinai Integrative Sleep Center, Division...",30791922
4,Katie L Stone,"Research Institute, California Pacific Medical...",31227429
...,...,...,...
15003,Patrick Tan,SingHealth Duke-NUS Institute of Precision Med...,35904853
15004,Weng Khong Lim,SingHealth Duke-NUS Institute of Precision Med...,35904853
15005,Ahmad Yusuf Kohestani,Institute of Diabetes and Clinical Metabolic R...,40022072
15006,Andre Franke,"Institute of Clinical Molecular Biology, Kiel ...",40022072
15007,Anju E Joham,Monash Centre for Health Research and Implemen...,37589624

In [ ]:
#verification des doublons
doublons = ecrire_reduit.duplicated(subset=['Auteur_nom', 'Auteur_affiliation', 'Article_pmid']).sum() 
print(f"Nombre de doublons : {doublons}")

Nombre de doublons : 0

#### Affilier

In [ ]:
# Relation Article ↔ Maladie
affilier = sommeil[['Maladie', 'PMID']].rename(columns={'Maladie': 'Maladie_nom', 'PMID': 'Article_pmid'}).drop_duplicates()

# Enregistrer en CSV
affilier.to_csv("affilier.csv", index=False)
affilier

      Maladie_nom  Article_pmid
0       Alzheimer      32657026
1       Alzheimer      35303225
2       Alzheimer      34109847
3       Alzheimer      30791922
4       Alzheimer      33136301
...           ...           ...
34959     Obesite      40022072
34960     Obesite      39587552
34961     Obesite      38778685
34963     Obesite      38837220
34966     Obesite      37589624

[20741 rows x 2 columns]

#### contenir

In [ ]:
# Extraction des relations Article ↔ Mots-clés
contenir_list = []
for row in sommeil[['PMID', 'Mots-clés']].dropna().values:
    pmid, mots = row
    for mot in mots.split(";"):
        contenir_list.append((mot.strip(), pmid))

# Création du DataFrame
contenir = pd.DataFrame(contenir_list, columns=['mots_cles', 'article_pmid']).drop_duplicates()
contenir['mots_cles'] = contenir['mots_cles'].apply(nettoyer_texte)

# Charger les fichiers CSV en renommant les colonnes
# alpha contient les mots clés avec leurs ids provenant de la bd oracle
alpha = pd.read_csv("alpha.csv").rename(columns={"ID_MC": "id_mc", "MOTS_CLES": "mots_cles"})
alpha.drop_duplicates(subset=['mots_cles'], keep='last', inplace=True)

# Fusionner les deux dataframes sur la colonne 'mots_cles'
motmots_cles = contenir.merge(alpha, on="mots_cles", how="left")



# Afficher le résultat

motmots_cles.to_csv("contenir.csv", index = False)
motmots_cles

                         mots_cles  article_pmid    id_mc
0               alzheimers disease      32657026  32451.0
1      amyloid cerebrospinal fluid      32657026  18554.0
2                            sleep      32657026   4301.0
3               alzheimers disease      35303225  32451.0
4                     amyloid beta      35303225  29884.0
...                            ...           ...      ...
92012    polycystic ovary syndrome      37589624  12337.0
92013                   assessment      37589624   3203.0
92014                evidencebased      37589624  12989.0
92015                    guideline      37589624  19555.0
92016                   management      37589624  11543.0

[92017 rows x 3 columns]